EduMartFYP1/Controllers/CollegeLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace EduMartFYP1.Controllers
{
    public class CollegeLoginController : Controller
    {
        // GET: CollegeLogin
        public ActionResult Login()
        {
            if (Session["username"] == null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Applications/Index");
            }
        }

        [HttpPost]
        public ActionResult Login(EduMartFYP1.Models.Cmembership model)
        {
            using (var Context = new EduMartEntities())
            {

                    bool isvalid = Context.College.Any(x => x.CollegeEmail == model.CollegeEmail && x.CollegePassword == model.CollegePassword);
                    if (isvalid)
                    {
                        var username = (from c in Context.College
                                        where c.CollegeEmail == model.CollegeEmail && c.CollegePassword == model.CollegePassword
                                        select c.CollegeName).FirstOrDefault();
                        var id = (from c in Context.College
                                  where c.CollegeEmail == model.CollegeEmail && c.CollegePassword == model.CollegePassword
                                  select c.CollegeID).FirstOrDefault();
                        Session["Collegeusername"] = username;
                        Session["Collegeid"] = id;
                        FormsAuthentication.SetAuthCookie(username, false);
                        return RedirectToAction("Index", "Applications/Index");
                    }
                    ModelState.AddModelError("", "Invalid Username and Password");
                    return View();

            }
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

    }
}

EduMartFYP1/Controllers/CollegesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EduMartFYP1;

namespace EduMartFYP1.Controllers
{
    public class CollegesController : Controller
    {
        private EduMartEntities db = new EduMartEntities();

        // GET: Colleges
        public ActionResult Index()
        {
            return View(db.College.ToList());
        }
        // GET: Colleges/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Colleges/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(College college)
        {
            using (var Context = new EduMartEntities())
            if (ModelState.IsValid)
            {
                var username = (from c in Context.College
                                where c.CollegeEmail == college.CollegeEmail && c.CollegePassword == college.CollegePassword
                                select c.CollegeName).FirstOrDefault();
                if (username == null)
                {
                    db.College.Add(college);
                    db.SaveChanges();
                    return RedirectToAction("Application/Index");
                }
                else
                {
                    ModelState.AddModelError("", "Email Already Exists");
                    return View();
                }
            }

            return View(college);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EduMartFYP1/Views/CollegeLogin/Login.cshtml
@model EduMartFYP1.Models.Cmembership

@{
    ViewBag.Title = "Login";
}

<!-- login -->
<div class="login-w3ls py-5">
    <div class="container py-xl-5 py-lg-3">
        <h3 class="title text-capitalize font-weight-light text-dark text-center mb-5">
            Login
            <span class="font-weight-bold">now</span>
        </h3>
        <!-- content -->
        <div class="sub-main-w3 pt-md-4">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-style-agile form-group">
                    <label>
                        Email
                        <i class="fas fa-envelope-open"></i>
                    </label>
                    @Html.EditorFor(model => model.CollegeEmail, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CollegeEmail, "", new { @class = "text-danger" })
                </div>
                <div class="form-style-agile form-group">
                    <label>
                        Password
                        <i class="fas fa-unlock-alt"></i>
                    </label>
                    @Html.PasswordFor(model => model.CollegePassword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CollegePassword, "", new { @class = "text-danger" })
                </div>
                <input type="submit" value="Log In">
                <p class="text-center dont-do mt-4 text-white">
                    Don't have an account?
                    @Html.ActionLink("Register Now", "Create", "Colleges", new object { }, new { @class = "text-white  font-weight-bold" })
                </p>
            }
        </div>
        <!-- //content -->
    </div>
</div>
<!-- //login -->